namespaceOverride: ingress-basic

ingress-nginx:
  controller:
    watchIngressWithoutClass: true
    hostPort:
      enabled: true
      http: 80
      https: 443
    service:
      externalTrafficPolicy: Local