apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: homepage
    server: https://kubernetes.default.svc # https://eztcaloadz-vkgfdjkq.hcp.eastus.azmk8s.io:443
  project: default
  source:
    repoURL: https://github.com/rodmhgl/app_of_apps
    path: manifests/homepage
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
