apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-all-clusters
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'nginx-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/rodmhgl/app_of_apps
        targetRevision: HEAD
        path: infra/nginx
        helm:
          valueFiles:
            - values-common.yaml
            - values-{{name}}.yaml
      destination:
        server: '{{server}}'
        namespace: ingress-basic
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      syncOptions:
      - CreateNamespace=true