kube-prometheus-stack:
  crds:
    enabled: true
  prometheus:
    ingress:
      ingressClassName: nginx
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod-dns"
      hosts:
        - prometheus.azurelaboratory.com
      tls:
        - secretName: prometheus-tls
          hosts:
            - prometheus.azurelaboratory.com
  grafana:
    ingress:
      ingressClassName: nginx
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod-dns"
      hosts:
        - grafana.azurelaboratory.com
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.azurelaboratory.com