apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-wordpress
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-wordpress
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://github.com/rodmhgl/argocd_apps/
    path: helm-wordpress
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
