apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testapp
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: testapp
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://github.com/rodmhgl/k8s_test_app
    path: kubernetes/manifests
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
