apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/rodmhgl
  services.yaml: |
    - My First Group:
        - Manifest k8s Test App:
            href: http://www.azurelaboratory.com/
            description: Test App deployed via manifest

    - My Second Group:
        - Kustomize k8s Test App:
            href: http://kustomize.azurelaboratory.com/
            description: Test App deployed via Kustomize

    - My Third Group:
        - Helm k8s Test App:
            href: http://helm.azurelaboratory.com/
            description: Test App deployed via Helm
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""