apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterrole_binding.yaml
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - serviceaccount.yaml

commonLabels:
  app: homepage
