cert-manager:
  namespace: cert-manager
  enableCertificateOwnerRef: true

  crds:
    enabled: true

  prometheus:
    enabled: false
  
  podLabels:
    azure.workload.identity/use: "true"

  serviceAccount:
    labels: